<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.gitconfig</string>
	</array>
	<key>name</key>
	<string>Git Configuration File (.gitconfig)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>section.name.gitconfig</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Configuration sections like [alias], [core], etc.</string>
			<key>match</key>
			<string>\[\w+\s*(".*")?\]</string>
			<key>name</key>
			<string>section.gitconfig</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>whitespace.gitconfig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.gitconfig</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Comments beginning with #.</string>
			<key>match</key>
			<string>^(\s*)(#.*)$</string>
			<key>name</key>
			<string>comment.gitconfig</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>whitespace.gitconfig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.quote.gitconfig</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>meta.property.gitconfig</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.quote.gitconfig</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.equals.gitconfig</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>meta.value.gitconfig</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation.quote.gitconfig</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>meta.value.gitconfig</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>punctuation.quote.gitconfig</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Key = value pair in the configuration file.</string>
			<key>match</key>
			<string>^(\s*(["']?)(.+?)(\2)\s*(=))?\s*((["']?)(.*?)(\7))\s*$</string>
			<key>name</key>
			<string>meta.declaration.gitconfig</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.gitconfig</string>
	<key>uuid</key>
	<string>7ddf7525-5056-4235-9423-08a78eca2e8c</string>
</dict>
</plist>
